name: Test
on: push

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8      

      - name: Run server JUnit tests
        run: bash ./gradlew test
        working-directory: ./server
 
      - name: Upload server test report
        uses: actions/upload-artifact@v2
        if: ${{ !cancelled() }}
        with:
          name: server-test-report
          path: /Users/runner/work/play-movies-2020-intern/play-movies-2020-intern/server/build/reports/tests/test/

      - name: Run app JUnit and Espresso tests
        uses: reactivecircus/android-emulator-runner@v2.11.0
        if: ${{ !cancelled() }}
        with:
          working-directory: ./MoviesTVSentiments
          api-level: 29
          script: |
            adb logcat -c
            adb logcat *:E &
            ./gradlew jacocoTestReport

      - name: Upload app test report
        uses: actions/upload-artifact@v2
        if: ${{ !cancelled() }}
        with:
          name: app-test-report
          path: /Users/runner/work/play-movies-2020-intern/play-movies-2020-intern/MoviesTVSentiments/app/build/reports/

